### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by EricZeiberg** [EricZeiberg/PowerStudent#3]
**TODO**
- [x] - Make add assignment work with weighted scoring
- [x] - Calculate GPA
- [ ] - Add ability to edit assignments
- [x] - Create new icons

~~\- [ ] - Notification system for new grades entered (maybe)'~~
- [x] - Add ability to remove rows
